version: '3.8'

services:
  openresty:
    image: openresty/openresty:1.21.4.1-0-alpine
    container_name: openresty-url-shortener
    ports:
      - "8082:80"    # Maps host port 80 to container port 80
      - "8083:443"  # Maps host port 443 to container port 443 (for SSL)
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf         # Maps the nginx.conf file directory to the container
    networks:
      - resty_network
    restart: unless-stopped

networks:
  resty_network:
    driver: bridge
